<?php session_start();
?>
<!DOCTYPE html>
<html lang="en"><head>
<link rel="icon" type="image/png" href="../../favicon.png?v=2">
<link rel="alternate icon" type="image/x-icon" href="../../favicon.ico?v=2"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Create Staff Account</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#faf6f0;font-family:Georgia,serif;color:#3b2313}.card{width:100%;max-width:520px;background:#fff;border:1px solid #e8ddd0;border-radius:14px;padding:26px;box-shadow:0 12px 38px rgba(59,35,19,.14)}h1{margin:0 0 6px}p{color:#7a6055;margin-top:0}.field{margin:12px 0}label{display:block;font-weight:800;margin-bottom:5px}input,select{width:100%;padding:10px;border:1px solid #e8ddd0;border-radius:8px;background:#faf6f0;font:inherit}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.btn{width:100%;margin-top:14px;padding:12px;border:1px solid #a9714a;background:#a9714a;color:#fff;border-radius:8px;font:inherit;font-weight:900;cursor:pointer}.msg{display:none;margin-top:14px;padding:10px;border-radius:8px}.ok{display:block;background:#e2ecdf;color:#4f7a4a}.err{display:block;background:#f6e3dc;color:#a8492f}</style>
<link rel="stylesheet" href="../../responsive-ui.css">
<link rel="stylesheet" href="../../dashboard-navigation.css">
<link rel="stylesheet" href="../../hrms-responsive.css">
</head><body><div class="card"><h1>Create Staff Account</h1><p>Use this after the applicant passes the final interview. Staff gets 8 hours/day fixed work setup.</p><div class="field"><label>Full name</label><input id="name"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="row"><div class="field"><label>Specific role</label><input id="role" placeholder="e.g. Barista, HR Staff"></div><div class="field"><label>Department</label><select id="department"><option>Human Resources</option><option>Operations</option><option>Sales</option><option>Engineering</option><option>Cafe</option></select></div></div><div class="row"><div class="field"><label>Fixed salary</label><input id="salary" type="number" min="0" step="0.01"></div><div class="field"><label>Staff password</label><input id="password" type="text" placeholder="e.g. staff123"></div></div><button class="btn" id="createBtn">Create staff login account</button><div class="msg" id="msg"></div></div><script>const msg=document.getElementById('msg');function show(t,ok){msg.textContent=t;msg.className='msg '+(ok?'ok':'err')}document.getElementById('createBtn').onclick=async()=>{const body={name:name.value.trim(),email:email.value.trim(),role:role.value.trim(),department:department.value,fixed_salary:salary.value,password:password.value.trim(),work_hours:8};if(!body.name||!body.email||!body.role||!body.fixed_salary||!body.password){show('Please complete all fields.',false);return}try{const r=await fetch('api/employees.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();show(d.success?`Staff account created. Username: ${d.username || body.email.split('@')[0]}`:(d.message||'Failed'),!!d.success)}catch(e){show('Backend error. Check Apache/MySQL.',false)}};</script>
<script src="../../responsive-ui.js" defer></script>
<script src="../../dashboard-navigation.js" defer></script>
<script src="../../hrms-responsive.js" defer></script>
</body></html>
